### ISSUE TITLE
Consider including Cargo.lock

### ISSUE THREAD

**Issue by fracek** [roynalnaruto/svm-rs#10]
The Cargo Books [recommends that end product applications ](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)(like cli tools) should include `Cargo.lock` into git. This makes the job of package maintainers easier (I'm making a package for NixOS).

**Comment by georgewhewell** [comment]
hey @fracek did you succeed in packaging this tool for nixos? i just tried to use it and (as expected) none of the binaries it downloads are functional. i think we need some sort of hook after it downloads a new version to patchelf the bin with nixos interpreter?

**Comment by fracek** [comment]
Yeah I haven't got around working on that. I was also wondering whta's the best way to force solc to look for the library in the right location.
