### ISSUE TITLE
Add support for emscripten-wasm32 platform

### ISSUE THREAD

**Issue by septaplex** [roynalnaruto/svm-rs#12]
Right now `svm-rs` doesn't support Apple Silicon.

We could add the `emscripten-wasm32` platform to fix this as Solidity WASM builds are create as part of the release process (see [here](https://github.com/ethereum/solidity/issues/12291#issuecomment-971665784)).

One can explore the WASM builds [here](https://github.com/ethereum/solc-bin/tree/gh-pages/emscripten-wasm32).

**Comment by roynalnaruto** [comment]
Added support in #25

**Comment by septaplex** [comment]
This is great! Thanks a lot for looking into it :+1:
