### ISSUE TITLE
support M1 0.8.13

### ISSUE THREAD

**Issue by gakonst** [roynalnaruto/svm-rs#32]
now that 0.8.13 is out, we need to get support for it here https://github.com/roynalnaruto/solc-builds/tree/master/macosx/aarch64 and then update svm for it!

**Comment by roynalnaruto** [comment]
Closing, added:
- https://github.com/roynalnaruto/solc-builds/commit/465839dcbb23fd4e60c16e8cae32513cd5627ca0
- https://github.com/roynalnaruto/svm-rs/commit/c32014f34308629cb1d98a8fdad29e527a8066d7

**Comment by gakonst** [comment]
Gg
