### ISSUE TITLE
nixos support

### ISSUE THREAD

**Issue by d-xo** [roynalnaruto/svm-rs#36]
The binaries provided by svm-rs are dynamically linked and therefore must be patched to work correctly on nixos. I currently work around this by using `DAPP_SOLC` to point forge to the nixos compatible solc versions that we provide as part of dapptools, but a more integrated experience would be great. 

Would you be open to supporting nixos directly in svm-rs? I would be happy to do the work and help maintain the integration.

**Comment by roynalnaruto** [comment]
> Would you be open to supporting nixos directly in svm-rs? I would be happy to do the work and help maintain the integration.

@d-xo For sure. Feel free to create a PR, and we can support nixos. I'm not that familiar with it, since I don't use it. But happy to include support in svm.

**Comment by d-xo** [comment]
That's great. Perhaps you could give me some pointers on how best to implement this?

I think the cleanest approach would be to apply, at runtime, a small patch to the binaries downloaded from soliditylang.org.

The patch would be applied via the instantiation of a nix expression. This would essentially boil down to a few invocations of nix command line tooling.

Which places in the code would need to be changed?

**Comment by roynalnaruto** [comment]
Closing as #48 was merged
