### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by agostbiro** [roynalnaruto/svm-rs#71]
Hi,

Sorry to bother you with this @roynalnaruto. I'm wondering if it'd be possible to cut a new release for #67, please? 

It'd be important to me, because currently I have to maintain my own fork of [ethers-rs](https://github.com/gakonst/ethers-rs) for [SealVault](https://github.com/sealvault/sealvault) due to conflicts in transitive dependencies which would be solved if `ethers-rs` depended on a version of `svm-rs` that includes #67. I'll make the PR in `ethers-rs` once there is a new release for `svm-rs`.

Let me know if I can do anything to help with the release!

Best,
Agost

**Comment by roynalnaruto** [comment]
Published new releases :)

**Comment by agostbiro** [comment]
Thank you so much!
